version: "3.7"

services:
  app:
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    build:
      context: ./ 
      dockerfile: Dockerfile
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgres-data
