version: "3.7"

services:
  server:
    container_name: my_store_api
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    build:
      context: ./server 
      dockerfile: Dockerfile
    depends_on: 
      - db
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /server

  db:
    container_name: my_store_db
    image: "postgres:${POSTGRES_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgres-data
    networks:
      - db-pgadmin-network
  pg_admin:
    image: dpage/pgadmin4
    restart: "always"
    env_file:
      - .env
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db-pgadmin-network

networks:
  db-pgadmin-network:
    driver: bridge

