version: "3.7"

services:
  app:
    build:
      context: ./app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - type: bind
        source: ./app
        target: /app
    restart: always
    depends_on:
      - server
      - db
  server:
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    build:
      context: ./server 
    depends_on: 
      - db
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /server

  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgres-data
