version: "3.7"

services:
  app:
    ports:
      - 3000:3000
    env_file:
      - .env
    build:
      context: ./ 
      dockerfile: Dockerfile
  db:
    image: postgres:10.5
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgres-data
